name: ravengis-env
channels:
- conda-forge
- defaults
dependencies:
  - python >=3.7
  - affine
  - click
  - fiona
  - gdal >=3.0.0
  - geopandas >=0.9
  - lxml
  - netcdf4
  - numpy
  - owslib
  - pandas
  - pip
  - pre-commit
  - pyproj >=3
  - rasterio
  - requests
  - rioxarray
  - scikit-learn >=0.24
  - setuptools >50.0
  - shapely
  - xarray >=0.18
  - wheel
